/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.92
 * Generated at: 2021-04-20 07:27:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dtr_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/layout/header.jsp", out, false);
      out.write("\r\n");
      out.write("\t<main>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/layout/nav.jsp", out, false);
      out.write("\r\n");
      out.write("            \r\n");
      out.write("             <div class=\"content\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div class=\"datetoday\">\r\n");
      out.write("                        <span>Date today :</span>\r\n");
      out.write("                        <h1 id=\"date-today\">DATE</h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"timeInAndOut\">\r\n");
      out.write("\t                    <form method=\"POST\" id=\"time-in\">\r\n");
      out.write("\t                    \t<input type=\"hidden\" name=\"username\"/>\r\n");
      out.write("\t                    \t<input type=\"hidden\" name=\"password\"/>\r\n");
      out.write("\t                    \t<input type=\"hidden\" value=\"time_in\" name=\"time_in\"/>\r\n");
      out.write("\t                    \t<input type=\"hidden\" value=\"\" name=\"employeeID\"/>\r\n");
      out.write("                        \t<input name=\"date_in\" class=\"timeInput\" type=\"text\" placeholder=\"- - Time In - -\" disabled>\r\n");
      out.write("                        </form>\r\n");
      out.write("                        <form method=\"POST\" id=\"time-out\">\r\n");
      out.write("                \t\t\t<input type=\"hidden\" name=\"username\"/>\r\n");
      out.write("\t                    \t<input type=\"hidden\" name=\"password\"/>\r\n");
      out.write("                        \t<input type=\"hidden\" value=\"time_out\" name=\"time_out\"/>\r\n");
      out.write("\t                    \t<input type=\"hidden\" value=\"\" name=\"employeeID\"/>\r\n");
      out.write("                        \t<input name=\"date_out\" class=\"timeInput\" type=\"text\" placeholder=\"- - Time Out - -\" disabled >\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"buttonCon\">\r\n");
      out.write("                        <input id=\"time-in-btn\" class=\"timeButton\" type=\"submit\" onclick=\"$('#time-in').submit()\" value=\"Time In\">\r\n");
      out.write("                        <input id=\"time-out-btn\" class=\"timeButton\" type=\"submit\"  onclick=\"$('#time-out').submit()\" value=\"Time Out\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <br><br>\r\n");
      out.write("                    <hr>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"dtrRecordCon\">\r\n");
      out.write("                        <h3>Your Daily Time Record History</h3>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <table>\r\n");
      out.write("                            <thead>\r\n");
      out.write("                                <th>Date</th>\r\n");
      out.write("                                <th>Time Span</th>\r\n");
      out.write("                                <th>Duration</th>\r\n");
      out.write("                            </thead>\r\n");
      out.write("                            <tbody id=\"dtr-body\">\r\n");
      out.write("                                \r\n");
      out.write("                            </tbody>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>                \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/script/dtr.js\"></script>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/layout/footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
