/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.92
 * Generated at: 2021-03-14 05:31:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class employee_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/layout/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"tableCon\">\r\n");
      out.write("            <h1>Employee</h1>\r\n");
      out.write("            <br>\r\n");
      out.write("            <form action=\"");
      out.print( request.getContextPath() );
      out.write("/update\" method=\"POST\" id=\"employee-form\">\r\n");
      out.write("            \t<input type=\"hidden\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employee.employeeID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("\t            <table class=\"view-employee-table\">\r\n");
      out.write("\t            \t<tr>\r\n");
      out.write("\t            \t\t<td>ID</td>\r\n");
      out.write("\t            \t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employee.employeeID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>\r\n");
      out.write("\t            \t</tr>\r\n");
      out.write("\t            \t<tr>\r\n");
      out.write("\t            \t\t<td>First Name</td>\r\n");
      out.write("\t            \t\t<td class=\"inputCon\">\r\n");
      out.write("\t            \t\t\t<input value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employee.firstname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" name=\"firstname\"/>\r\n");
      out.write("\t            \t\t</td>\r\n");
      out.write("\t            \t</tr>\r\n");
      out.write("\t            \t<tr>\r\n");
      out.write("\t            \t\t<td>Last Name</td>\r\n");
      out.write("\t            \t\t<td class=\"inputCon\">\r\n");
      out.write("\t            \t\t\t<input value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employee.lastname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" name=\"lastname\"/>\r\n");
      out.write("\t            \t\t</td>\r\n");
      out.write("\t            \t</tr>\r\n");
      out.write("\t            \t<tr>\r\n");
      out.write("\t            \t\t<td>MI</td>\r\n");
      out.write("\t            \t\t<td class=\"inputCon\">\r\n");
      out.write("\t            \t\t\t<input value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employee.mi}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" name=\"mi\"/>\r\n");
      out.write("\t            \t\t</td>\r\n");
      out.write("\t            \t</tr>\r\n");
      out.write("\t            \t<tr>\r\n");
      out.write("\t            \t\t<td>Email</td>\r\n");
      out.write("\t            \t\t<td class=\"inputCon\">\r\n");
      out.write("\t            \t\t\t<input value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employee.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" type=\"email\" name=\"email\"/>\r\n");
      out.write("\t            \t\t</td>\r\n");
      out.write("\t            \t</tr>\r\n");
      out.write("\t            \t<tr>\r\n");
      out.write("\t            \t\t<td>Username</td>\r\n");
      out.write("\t            \t\t<td class=\"inputCon\">\r\n");
      out.write("\t            \t\t\t<input value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employee.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" name=\"username\"/>\r\n");
      out.write("\t            \t\t</td>\r\n");
      out.write("\t            \t</tr>\r\n");
      out.write("\t            \t<tr>\r\n");
      out.write("\t            \t\t<td>Password</td>\r\n");
      out.write("\t            \t\t<td class=\"inputCon\">\r\n");
      out.write("\t            \t\t\t<input value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employee.password}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" name=\"password\"/>\r\n");
      out.write("\t            \t\t</td>\r\n");
      out.write("\t            \t</tr>\r\n");
      out.write("\t            \t<tr>\r\n");
      out.write("\t            \t\t<td>Action</td>\r\n");
      out.write("\t            \t\t<td>\r\n");
      out.write("\t\t            \t\t<a class=\"button-link\" onclick='document.querySelector(\"#employee-form\").submit()'>\r\t\t\t\t\t\tUpdate\t\t\t\t\t        \t\t\r\n");
      out.write("\t\t\t\t        \t</a>\r\n");
      out.write("\t            \t\t\t<a class=\"button-link\" href=\"");
      out.print(request.getContextPath() );
      out.write("/delete?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employee.employeeID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\tDelete\t\t\t\t\t        \t\t\r\n");
      out.write("\t\t\t\t        \t</a>\r\n");
      out.write("\t\t\t        \t</td>\r\n");
      out.write("\t            \t</tr>\r\n");
      out.write("\t            </table>\r\n");
      out.write("            </form>\r\n");
      out.write("</div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/layout/footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
